import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const america = localFont({
  src: "./fonts/GT-America-Regular.woff2",
  variable: "--font-america",
  weight: "500",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${america.variable}`}>{children}</body>
    </html>
  );
}
